"""
Congruity Framework Core

Experiment Context

Every experiment exchanges exactly one object.

No module accesses configuration files or datasets directly.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import pandas as pd

from congruity.identity.models import (
    IdentityDeclaration,
)


@dataclass
class ExperimentContext:
    """
    Shared execution context.

    Every stage of the framework receives the same object and
    returns the same object with additional validated information.
    """

    experiment_id: str

    configuration: dict[str, Any]

    identity: IdentityDeclaration

    feature_table: pd.DataFrame

    metadata: dict[str, Any] = field(
        default_factory=dict
    )

    provenance: dict[str, Any] = field(
        default_factory=dict
    )

    runtime: dict[str, Any] = field(
        default_factory=dict
    )

    outputs: dict[str, Any] = field(
        default_factory=dict
    )

    working_directory: Path | None = None

    def register_output(
        self,
        name: str,
        value: Any,
    ) -> None:
        """
        Store an output generated by one stage.
        """
        self.outputs[name] = value

    def register_runtime(
        self,
        name: str,
        value: Any,
    ) -> None:
        """
        Store runtime information.
        """
        self.runtime[name] = value

    def register_metadata(
        self,
        name: str,
        value: Any,
    ) -> None:
        """
        Store experiment metadata.
        """
        self.metadata[name] = value

    def register_provenance(
        self,
        name: str,
        value: Any,
    ) -> None:
        """
        Store provenance information.
        """
        self.provenance[name] = value
