"""
CGIE3-ID-02 frozen relation-classification stage.

This module merges the evidence generated by the preceding stages
and applies only the thresholds frozen in:

    engines/cgie3/config/
    cgie3_id_02_relation_discovery.yaml

Every relation receives exactly one status:

- eligible;
- candidate;
- rejected;
- non_estimable.

This module does not:

- alter thresholds;
- identify primary or indispensable relations;
- use evaluation-period or target-event information;
- infer causality;
- establish predictive capability.
"""

from __future__ import annotations

from typing import Any, Mapping

import numpy as np
import pandas as pd

from congruity.core import ExperimentContext


class ClassificationStageError(ValueError):
    """Raised when classification violates the frozen contract."""


def fail(message: str) -> None:
    """Raise a classification-stage error."""
    raise ClassificationStageError(
        str(message).strip()
    )


def require_mapping(
    value: Any,
    field_name: str,
) -> Mapping[str, Any]:
    """Require a mapping-like configuration value."""
    if not isinstance(value, Mapping):
        fail(
            f"{field_name} must be a mapping."
        )

    return value


def require_fraction(
    value: Any,
    field_name: str,
) -> float:
    """Require a numeric fraction inside [0, 1]."""
    try:
        normalized = float(value)
    except (
        TypeError,
        ValueError,
    ) as exc:
        raise ClassificationStageError(
            f"{field_name} must be numeric."
        ) from exc

    if not 0.0 <= normalized <= 1.0:
        fail(
            f"{field_name} must lie inside [0, 1]."
        )

    return normalized


def require_non_negative_float(
    value: Any,
    field_name: str,
) -> float:
    """Require a finite non-negative float."""
    try:
        normalized = float(value)
    except (
        TypeError,
        ValueError,
    ) as exc:
        raise ClassificationStageError(
            f"{field_name} must be numeric."
        ) from exc

    if (
        not np.isfinite(normalized)
        or normalized < 0.0
    ):
        fail(
            f"{field_name} must be finite "
            "and non-negative."
        )

    return normalized


def require_dataframe(
    value: Any,
    field_name: str,
) -> pd.DataFrame:
    """Require a non-empty pandas DataFrame."""
    if not isinstance(
        value,
        pd.DataFrame,
    ):
        fail(
            f"{field_name} must be a pandas DataFrame."
        )

    if value.empty:
        fail(
            f"{field_name} must not be empty."
        )

    return value


def validate_context(
    context: ExperimentContext,
) -> None:
    """Validate classification-stage prerequisites."""
    if not isinstance(
        context,
        ExperimentContext,
    ):
        fail(
            "context must be an ExperimentContext."
        )

    if context.experiment_id != "CGIE3_ID_02":
        fail(
            "Unexpected experiment ID: "
            f"{context.experiment_id}"
        )

    required_outputs = {
        "candidate_relations",
        "relation_persistence",
        "leave_one_block_out",
        "bootstrap_summary",
        "missingness_summary",
    }

    missing_outputs = sorted(
        required_outputs
        - set(context.outputs)
    )

    if missing_outputs:
        fail(
            "Classification prerequisites are missing: "
            + ", ".join(missing_outputs)
        )


def get_classification_contract(
    context: ExperimentContext,
) -> dict[str, Any]:
    """Extract the frozen classification thresholds."""
    classification = require_mapping(
        context.configuration.get(
            "classification"
        ),
        "classification",
    )

    allowed_statuses = classification.get(
        "allowed_statuses"
    )

    expected_statuses = {
        "eligible",
        "candidate",
        "rejected",
        "non_estimable",
    }

    if not isinstance(
        allowed_statuses,
        (list, tuple),
    ):
        fail(
            "classification.allowed_statuses "
            "must be a list."
        )

    if set(allowed_statuses) != expected_statuses:
        fail(
            "Frozen allowed statuses differ from "
            "the CGIE3-ID-02 contract."
        )

    if (
        classification.get(
            "essential_status_allowed"
        )
        is not False
    ):
        fail(
            "Essential status must remain prohibited."
        )

    if (
        classification.get(
            "primary_status_allowed"
        )
        is not False
    ):
        fail(
            "Primary status must remain prohibited."
        )

    if (
        classification.get(
            "secondary_status_allowed"
        )
        is not False
    ):
        fail(
            "Secondary status must remain prohibited."
        )

    strength = require_mapping(
        context.configuration.get(
            "strength"
        ),
        "strength",
    )

    persistence = require_mapping(
        context.configuration.get(
            "persistence"
        ),
        "persistence",
    )

    uncertainty = require_mapping(
        context.configuration.get(
            "uncertainty"
        ),
        "uncertainty",
    )

    return {
        "eligible_strength":
            require_non_negative_float(
                strength.get(
                    "minimum_full_baseline_"
                    "absolute_strength_for_eligible"
                ),
                "strength.minimum_full_baseline_"
                "absolute_strength_for_eligible",
            ),
        "candidate_strength":
            require_non_negative_float(
                strength.get(
                    "minimum_full_baseline_"
                    "absolute_strength_for_candidate"
                ),
                "strength.minimum_full_baseline_"
                "absolute_strength_for_candidate",
            ),
        "eligible_persistence":
            require_fraction(
                persistence.get(
                    "minimum_persistence_for_eligible"
                ),
                "persistence."
                "minimum_persistence_for_eligible",
            ),
        "candidate_persistence":
            require_fraction(
                persistence.get(
                    "minimum_persistence_for_candidate"
                ),
                "persistence."
                "minimum_persistence_for_candidate",
            ),
        "minimum_estimable_block_fraction":
            require_fraction(
                persistence.get(
                    "minimum_estimable_block_fraction"
                ),
                "persistence."
                "minimum_estimable_block_fraction",
            ),
        "minimum_sign_preservation_fraction":
            require_fraction(
                persistence.get(
                    "minimum_sign_preservation_fraction"
                ),
                "persistence."
                "minimum_sign_preservation_fraction",
            ),
        "eligible_maximum_ci_width":
            require_non_negative_float(
                uncertainty.get(
                    "maximum_confidence_interval_"
                    "width_for_eligible"
                ),
                "uncertainty.maximum_confidence_"
                "interval_width_for_eligible",
            ),
        "candidate_maximum_ci_width":
            require_non_negative_float(
                uncertainty.get(
                    "maximum_confidence_interval_"
                    "width_for_candidate"
                ),
                "uncertainty.maximum_confidence_"
                "interval_width_for_candidate",
            ),
        "eligible_interval_requires_sign":
            bool(
                uncertainty.get(
                    "confidence_interval_must_"
                    "exclude_opposite_sign_for_eligible"
                )
            ),
    }


def validate_unique_keys(
    frame: pd.DataFrame,
    field_name: str,
) -> None:
    """Validate one row per window-relation key."""
    required_columns = {
        "window_id",
        "relation_id",
    }

    missing_columns = sorted(
        required_columns
        - set(frame.columns)
    )

    if missing_columns:
        fail(
            f"{field_name} is missing key columns: "
            + ", ".join(missing_columns)
        )

    duplicate_mask = frame.duplicated(
        subset=[
            "window_id",
            "relation_id",
        ],
        keep=False,
    )

    if duplicate_mask.any():
        fail(
            f"{field_name} contains duplicate "
            "window-relation keys."
        )


def merge_classification_evidence(
    context: ExperimentContext,
) -> pd.DataFrame:
    """Merge all frozen evidence into one relation table."""
    candidates = require_dataframe(
        context.outputs[
            "candidate_relations"
        ],
        "candidate_relations",
    ).copy()

    persistence = require_dataframe(
        context.outputs[
            "relation_persistence"
        ],
        "relation_persistence",
    ).copy()

    leave_one_out = require_dataframe(
        context.outputs[
            "leave_one_block_out"
        ],
        "leave_one_block_out",
    ).copy()

    bootstrap = require_dataframe(
        context.outputs[
            "bootstrap_summary"
        ],
        "bootstrap_summary",
    ).copy()

    missingness = require_dataframe(
        context.outputs[
            "missingness_summary"
        ],
        "missingness_summary",
    ).copy()

    for name, frame in (
        ("candidate_relations", candidates),
        ("relation_persistence", persistence),
        ("leave_one_block_out", leave_one_out),
        ("bootstrap_summary", bootstrap),
        ("missingness_summary", missingness),
    ):
        validate_unique_keys(
            frame,
            name,
        )

        if len(frame) != 136:
            fail(
                f"{name} must contain 136 rows; "
                f"observed {len(frame)}."
            )

    candidate_columns = [
        "experiment_id",
        "window_id",
        "relation_id",
        "source_id",
        "target_id",
        "estimator_id",
        "direction",
        "estimability",
        "strength",
        "absolute_strength",
        "sign",
        "sample_count",
        "p_value",
        "non_estimable_reason",
    ]

    missing_candidate_columns = sorted(
        set(candidate_columns)
        - set(candidates.columns)
    )

    if missing_candidate_columns:
        fail(
            "candidate_relations is missing columns: "
            + ", ".join(
                missing_candidate_columns
            )
        )

    evidence = candidates.loc[
        :,
        candidate_columns,
    ].copy()

    persistence_columns = [
        "window_id",
        "relation_id",
        "valid_block_count",
        "minimum_valid_blocks_met",
        "estimable_block_fraction",
        "sign_preservation_fraction",
        "strength_preservation_fraction",
        "persistence",
        "median_block_strength",
        "median_block_absolute_strength",
    ]

    evidence = evidence.merge(
        persistence[
            persistence_columns
        ],
        on=[
            "window_id",
            "relation_id",
        ],
        how="left",
        validate="one_to_one",
    )

    loo_columns = [
        "window_id",
        "relation_id",
        "loo_estimable_count",
        "loo_sign_preservation_fraction",
        "loo_median_absolute_strength_change",
        "leave_one_block_out_robust",
    ]

    evidence = evidence.merge(
        leave_one_out[
            loo_columns
        ],
        on=[
            "window_id",
            "relation_id",
        ],
        how="left",
        validate="one_to_one",
    )

    bootstrap_columns = [
        "window_id",
        "relation_id",
        "bootstrap_estimable_count",
        "bootstrap_estimable_fraction",
        "bootstrap_ci_lower",
        "bootstrap_ci_upper",
        "bootstrap_ci_width",
        "bootstrap_interval_crosses_zero",
        "bootstrap_interval_supports_full_sign",
        "bootstrap_sign_support_fraction",
    ]

    evidence = evidence.merge(
        bootstrap[
            bootstrap_columns
        ],
        on=[
            "window_id",
            "relation_id",
        ],
        how="left",
        validate="one_to_one",
    )

    missingness_columns = [
        "window_id",
        "relation_id",
        "missingness_estimable_count",
        "missingness_estimable_fraction",
        "missingness_sign_preservation_fraction",
        "missingness_median_absolute_strength_change",
        "missingness_stress_robust",
    ]

    evidence = evidence.merge(
        missingness[
            missingness_columns
        ],
        on=[
            "window_id",
            "relation_id",
        ],
        how="left",
        validate="one_to_one",
    )

    if len(evidence) != 136:
        fail(
            "Merged classification evidence must "
            f"contain 136 rows; observed {len(evidence)}."
        )

    return evidence


def safe_boolean(
    value: Any,
) -> bool:
    """Convert missing values to False and valid values to bool."""
    if value is None:
        return False

    try:
        if pd.isna(value):
            return False
    except (
        TypeError,
        ValueError,
    ):
        pass

    return bool(value)


def safe_threshold(
    value: Any,
    *,
    minimum: float | None = None,
    maximum: float | None = None,
) -> bool:
    """Evaluate a finite value against optional thresholds."""
    if value is None:
        return False

    try:
        normalized = float(value)
    except (
        TypeError,
        ValueError,
    ):
        return False

    if not np.isfinite(normalized):
        return False

    if (
        minimum is not None
        and normalized < minimum
    ):
        return False

    if (
        maximum is not None
        and normalized > maximum
    ):
        return False

    return True


def classify_relation(
    row: Any,
    contract: Mapping[str, Any],
) -> dict[str, Any]:
    """Apply frozen precedence and classification rules to one relation."""
    full_baseline_estimable = (
        row.estimability
        == "estimable"
        and row.strength is not None
        and not pd.isna(row.strength)
    )

    conditions = {
        "estimable_on_full_baseline":
            full_baseline_estimable,
        "eligible_strength":
            safe_threshold(
                row.absolute_strength,
                minimum=contract[
                    "eligible_strength"
                ],
            ),
        "candidate_strength":
            safe_threshold(
                row.absolute_strength,
                minimum=contract[
                    "candidate_strength"
                ],
            ),
        "minimum_valid_blocks_met":
            safe_boolean(
                row.minimum_valid_blocks_met
            ),
        "eligible_estimable_block_fraction":
            safe_threshold(
                row.estimable_block_fraction,
                minimum=contract[
                    "minimum_estimable_block_fraction"
                ],
            ),
        "eligible_sign_preservation":
            safe_threshold(
                row.sign_preservation_fraction,
                minimum=contract[
                    "minimum_sign_preservation_fraction"
                ],
            ),
        "eligible_persistence":
            safe_threshold(
                row.persistence,
                minimum=contract[
                    "eligible_persistence"
                ],
            ),
        "candidate_persistence":
            safe_threshold(
                row.persistence,
                minimum=contract[
                    "candidate_persistence"
                ],
            ),
        "eligible_ci_width":
            safe_threshold(
                row.bootstrap_ci_width,
                maximum=contract[
                    "eligible_maximum_ci_width"
                ],
            ),
        "candidate_ci_width":
            safe_threshold(
                row.bootstrap_ci_width,
                maximum=contract[
                    "candidate_maximum_ci_width"
                ],
            ),
        "eligible_interval_sign_support":
            (
                safe_boolean(
                    row.bootstrap_interval_supports_full_sign
                )
                if contract[
                    "eligible_interval_requires_sign"
                ]
                else True
            ),
        "leave_one_block_out_robust":
            safe_boolean(
                row.leave_one_block_out_robust
            ),
        "missingness_stress_robust":
            safe_boolean(
                row.missingness_stress_robust
            ),
    }

    eligible_conditions = (
        conditions[
            "estimable_on_full_baseline"
        ],
        conditions[
            "eligible_strength"
        ],
        conditions[
            "minimum_valid_blocks_met"
        ],
        conditions[
            "eligible_estimable_block_fraction"
        ],
        conditions[
            "eligible_sign_preservation"
        ],
        conditions[
            "eligible_persistence"
        ],
        conditions[
            "eligible_ci_width"
        ],
        conditions[
            "eligible_interval_sign_support"
        ],
        conditions[
            "leave_one_block_out_robust"
        ],
        conditions[
            "missingness_stress_robust"
        ],
    )

    candidate_conditions = (
        conditions[
            "estimable_on_full_baseline"
        ],
        conditions[
            "candidate_strength"
        ],
        conditions[
            "candidate_persistence"
        ],
        conditions[
            "candidate_ci_width"
        ],
    )

    if not full_baseline_estimable:
        status = "non_estimable"

        reason = (
            row.non_estimable_reason
            if isinstance(
                row.non_estimable_reason,
                str,
            )
            and row.non_estimable_reason.strip()
            else "full_baseline_non_estimable"
        )
    elif all(
        eligible_conditions
    ):
        status = "eligible"
        reason = "all_frozen_eligible_conditions_met"
    elif all(
        candidate_conditions
    ):
        status = "candidate"
        reason = "candidate_conditions_met"
    else:
        status = "rejected"
        reason = "eligible_and_candidate_conditions_not_met"

    failed_eligible_conditions = [
        name
        for name in (
            "estimable_on_full_baseline",
            "eligible_strength",
            "minimum_valid_blocks_met",
            "eligible_estimable_block_fraction",
            "eligible_sign_preservation",
            "eligible_persistence",
            "eligible_ci_width",
            "eligible_interval_sign_support",
            "leave_one_block_out_robust",
            "missingness_stress_robust",
        )
        if not conditions[name]
    ]

    failed_candidate_conditions = [
        name
        for name in (
            "estimable_on_full_baseline",
            "candidate_strength",
            "candidate_persistence",
            "candidate_ci_width",
        )
        if not conditions[name]
    ]

    return {
        "classification_status":
            status,
        "classification_reason":
            reason,
        "eligible_condition_count_met":
            int(
                sum(
                    bool(value)
                    for value
                    in eligible_conditions
                )
            ),
        "eligible_condition_count_total":
            int(len(eligible_conditions)),
        "candidate_condition_count_met":
            int(
                sum(
                    bool(value)
                    for value
                    in candidate_conditions
                )
            ),
        "candidate_condition_count_total":
            int(len(candidate_conditions)),
        "failed_eligible_conditions":
            "|".join(
                failed_eligible_conditions
            ),
        "failed_candidate_conditions":
            "|".join(
                failed_candidate_conditions
            ),
        **{
            f"condition_{name}":
                bool(value)
            for name, value
            in conditions.items()
        },
    }


def apply_classification(
    evidence: pd.DataFrame,
    contract: Mapping[str, Any],
) -> pd.DataFrame:
    """Classify every relation deterministically."""
    classification_records = [
        classify_relation(
            row,
            contract,
        )
        for row in evidence.itertuples(
            index=False
        )
    ]

    classification_frame = (
        pd.DataFrame.from_records(
            classification_records
        )
    )

    if len(classification_frame) != len(
        evidence
    ):
        fail(
            "Classification output count differs "
            "from evidence count."
        )

    output = pd.concat(
        [
            evidence.reset_index(
                drop=True
            ),
            classification_frame.reset_index(
                drop=True
            ),
        ],
        axis=1,
    )

    allowed_statuses = {
        "eligible",
        "candidate",
        "rejected",
        "non_estimable",
    }

    observed_statuses = set(
        output[
            "classification_status"
        ].unique()
    )

    unexpected_statuses = sorted(
        observed_statuses
        - allowed_statuses
    )

    if unexpected_statuses:
        fail(
            "Unexpected classification statuses: "
            + ", ".join(
                unexpected_statuses
            )
        )

    duplicate_mask = output.duplicated(
        subset=[
            "window_id",
            "relation_id",
        ],
        keep=False,
    )

    if duplicate_mask.any():
        fail(
            "Classification output contains "
            "duplicate window-relation keys."
        )

    return output.sort_values(
        by=[
            "window_id",
            "source_id",
            "target_id",
            "relation_id",
        ],
        kind="stable",
    ).reset_index(
        drop=True
    )


def build_classification_summary(
    classification: pd.DataFrame,
) -> dict[str, Any]:
    """Build the frozen classification summary."""
    status_counts = (
        classification[
            "classification_status"
        ]
        .value_counts()
        .reindex(
            [
                "eligible",
                "candidate",
                "rejected",
                "non_estimable",
            ],
            fill_value=0,
        )
        .to_dict()
    )

    by_window: dict[str, Any] = {}

    for window_id, frame in (
        classification.groupby(
            "window_id",
            sort=True,
        )
    ):
        counts = (
            frame[
                "classification_status"
            ]
            .value_counts()
            .reindex(
                [
                    "eligible",
                    "candidate",
                    "rejected",
                    "non_estimable",
                ],
                fill_value=0,
            )
            .to_dict()
        )

        by_window[str(window_id)] = {
            str(key): int(value)
            for key, value
            in counts.items()
        }

    non_estimable_reasons = (
        classification.loc[
            classification[
                "classification_status"
            ]
            == "non_estimable",
            "classification_reason",
        ]
        .fillna("unspecified")
        .value_counts()
        .sort_index()
        .to_dict()
    )

    eligible_count = int(
        status_counts["eligible"]
    )

    if eligible_count > 0:
        scientific_outcome = (
            "eligible_relations_identified"
        )
    elif int(
        status_counts["candidate"]
    ) > 0:
        scientific_outcome = (
            "only_candidate_relations"
        )
    elif int(
        status_counts["non_estimable"]
    ) == len(classification):
        scientific_outcome = (
            "all_relations_non_estimable"
        )
    else:
        scientific_outcome = (
            "no_eligible_relations"
        )

    return {
        "status":
            "COMPLETED",
        "technical_success":
            True,
        "relation_count":
            int(len(classification)),
        "status_counts": {
            str(key): int(value)
            for key, value
            in status_counts.items()
        },
        "by_window":
            by_window,
        "non_estimable_reasons": {
            str(key): int(value)
            for key, value
            in non_estimable_reasons.items()
        },
        "scientific_outcome":
            scientific_outcome,
        "scientific_positive_result":
            bool(
                eligible_count > 0
            ),
        "primary_relations_established":
            False,
        "indispensable_relations_established":
            False,
        "causality_established":
            False,
        "predictive_capability_established":
            False,
        "earthquake_prediction_established":
            False,
    }


def classify_relations(
    context: ExperimentContext,
) -> ExperimentContext:
    """Execute frozen CGIE3-ID-02 relation classification."""
    validate_context(
        context
    )

    contract = get_classification_contract(
        context
    )

    evidence = merge_classification_evidence(
        context
    )

    classification = apply_classification(
        evidence,
        contract,
    )

    if len(classification) != 136:
        fail(
            "Relation classification must contain "
            f"136 rows; observed {len(classification)}."
        )

    summary = build_classification_summary(
        classification
    )

    context.register_output(
        "classification_evidence",
        evidence,
    )

    context.register_output(
        "relation_classification",
        classification,
    )

    context.register_output(
        "classification_summary",
        summary,
    )

    context.register_runtime(
        "classification_status",
        "COMPLETED",
    )

    return context
 
  
