"""
CGIE3-ID-02 reporting stage.

This module writes the frozen scientific outputs generated by the
preceding experiment stages.

It does not:

- recompute relations;
- alter classifications;
- change thresholds;
- remove negative or non-estimable results;
- infer causality or predictive capability.
"""

from __future__ import annotations

import hashlib
import json
import platform
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Mapping

import numpy as np
import pandas as pd

from congruity.core import (
    ExperimentContext,
    ExperimentResult,
)


class ReportingStageError(ValueError):
    """Raised when reporting violates the frozen experiment contract."""


SCRIPT_PATH = Path(__file__).resolve()
REPOSITORY_ROOT = SCRIPT_PATH.parents[4]
OUTPUT_DIRECTORY = REPOSITORY_ROOT / "outputs"


OUTPUT_PATHS = {
    "candidate_relations":
        OUTPUT_DIRECTORY
        / "CGIE3_ID_02_candidate_relations.csv",

    "block_relations":
        OUTPUT_DIRECTORY
        / "CGIE3_ID_02_block_relations.csv",

    "bootstrap_relations":
        OUTPUT_DIRECTORY
        / "CGIE3_ID_02_bootstrap_relations.csv",

    "relation_classification":
        OUTPUT_DIRECTORY
        / "CGIE3_ID_02_relation_classification.csv",

    "equivalence_flags":
        OUTPUT_DIRECTORY
        / "CGIE3_ID_02_equivalence_flags.csv",

    "summary":
        OUTPUT_DIRECTORY
        / "CGIE3_ID_02_summary.json",

    "report":
        OUTPUT_DIRECTORY
        / "CGIE3_ID_02_report.md",

    "manifest":
        OUTPUT_DIRECTORY
        / "CGIE3_ID_02_manifest.json",
}


def fail(message: str) -> None:
    """Raise a reporting-stage error."""
    raise ReportingStageError(
        str(message).strip()
    )


def utc_now_iso() -> str:
    """Return current UTC time in canonical ISO-8601 format."""
    return (
        datetime.now(timezone.utc)
        .isoformat()
        .replace("+00:00", "Z")
    )


def require_mapping(
    value: Any,
    field_name: str,
) -> Mapping[str, Any]:
    """Require a mapping-like value."""
    if not isinstance(value, Mapping):
        fail(
            f"{field_name} must be a mapping."
        )

    return value


def require_dataframe(
    value: Any,
    field_name: str,
) -> pd.DataFrame:
    """Require a non-empty pandas DataFrame."""
    if not isinstance(
        value,
        pd.DataFrame,
    ):
        fail(
            f"{field_name} must be a pandas DataFrame."
        )

    if value.empty:
        fail(
            f"{field_name} must not be empty."
        )

    return value


def validate_context(
    context: ExperimentContext,
) -> None:
    """Validate all reporting-stage prerequisites."""
    if not isinstance(
        context,
        ExperimentContext,
    ):
        fail(
            "context must be an ExperimentContext."
        )

    if context.experiment_id != "CGIE3_ID_02":
        fail(
            "Unexpected experiment ID: "
            f"{context.experiment_id}"
        )

    required_outputs = {
        "candidate_relations",
        "block_relations",
        "bootstrap_replicates",
        "relation_classification",
        "equivalence_flags",
        "relation_discovery_summary",
        "persistence_summary",
        "bootstrap_stage_summary",
        "missingness_stage_summary",
        "classification_summary",
        "equivalence_summary",
        "preprocessing_quality_audit",
    }

    missing_outputs = sorted(
        required_outputs
        - set(context.outputs)
    )

    if missing_outputs:
        fail(
            "Reporting prerequisites are missing: "
            + ", ".join(missing_outputs)
        )

    required_runtime_stages = {
        "preprocessing_status",
        "relation_discovery_status",
        "persistence_status",
        "bootstrap_status",
        "missingness_status",
        "classification_status",
        "equivalence_status",
    }

    missing_runtime = sorted(
        required_runtime_stages
        - set(context.runtime)
    )

    if missing_runtime:
        fail(
            "Runtime stage records are missing: "
            + ", ".join(missing_runtime)
        )

    incomplete_stages = sorted(
        stage_name
        for stage_name
        in required_runtime_stages
        if context.runtime.get(stage_name)
        != "COMPLETED"
    )

    if incomplete_stages:
        fail(
            "Some experiment stages are not completed: "
            + ", ".join(incomplete_stages)
        )


def sha256_file(
    path: Path,
) -> str:
    """Calculate SHA-256 for one file."""
    if not path.exists():
        fail(
            f"File not found for hashing: {path}"
        )

    digest = hashlib.sha256()

    with path.open("rb") as handle:
        for block in iter(
            lambda: handle.read(
                1024 * 1024
            ),
            b"",
        ):
            digest.update(block)

    return digest.hexdigest()


def json_compatible(
    value: Any,
) -> Any:
    """
    Convert framework objects into strict JSON-compatible structures.

    Non-finite floating-point values become null.
    """
    if value is None:
        return None

    if isinstance(
        value,
        (
            str,
            bool,
            int,
        ),
    ):
        return value

    if isinstance(
        value,
        (
            np.integer,
        ),
    ):
        return int(value)

    if isinstance(
        value,
        (
            float,
            np.floating,
        ),
    ):
        normalized = float(value)

        if not np.isfinite(
            normalized
        ):
            return None

        return normalized

    if isinstance(
        value,
        pd.Timestamp,
    ):
        return value.isoformat()

    if isinstance(
        value,
        Path,
    ):
        return str(value)

    if isinstance(
        value,
        Mapping,
    ):
        return {
            str(key): json_compatible(item)
            for key, item
            in value.items()
        }

    if isinstance(
        value,
        (
            list,
            tuple,
            set,
        ),
    ):
        return [
            json_compatible(item)
            for item in value
        ]

    if hasattr(
        value,
        "__dataclass_fields__",
    ):
        return {
            field_name: json_compatible(
                getattr(
                    value,
                    field_name,
                )
            )
            for field_name
            in value.__dataclass_fields__
        }

    return str(value)


def write_json(
    path: Path,
    payload: Mapping[str, Any],
) -> None:
    """Write strict deterministic JSON."""
    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    compatible_payload = (
        json_compatible(
            payload
        )
    )

    path.write_text(
        json.dumps(
            compatible_payload,
            indent=2,
            ensure_ascii=False,
            sort_keys=True,
            allow_nan=False,
        )
        + "\n",
        encoding="utf-8",
    )


def write_csv(
    path: Path,
    frame: pd.DataFrame,
) -> None:
    """Write deterministic UTF-8 CSV."""
    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    output = frame.copy()

    for column in output.columns:
        if output[column].map(
            lambda value: isinstance(
                value,
                (
                    dict,
                    list,
                    tuple,
                    set,
                ),
            )
        ).any():
            output[column] = output[
                column
            ].map(
                lambda value: json.dumps(
                    json_compatible(value),
                    ensure_ascii=False,
                    sort_keys=True,
                )
                if isinstance(
                    value,
                    (
                        dict,
                        list,
                        tuple,
                        set,
                    ),
                )
                else value
            )

    output.to_csv(
        path,
        index=False,
        encoding="utf-8",
        lineterminator="\n",
        float_format="%.10g",
    )


def validate_output_row_counts(
    context: ExperimentContext,
) -> None:
    """Validate row counts before writing official outputs."""
    candidate_relations = (
        require_dataframe(
            context.outputs[
                "candidate_relations"
            ],
            "candidate_relations",
        )
    )

    classification = require_dataframe(
        context.outputs[
            "relation_classification"
        ],
        "relation_classification",
    )

    equivalence_flags = require_dataframe(
        context.outputs[
            "equivalence_flags"
        ],
        "equivalence_flags",
    )

    if len(
        candidate_relations
    ) != 136:
        fail(
            "candidate_relations must contain 136 rows."
        )

    if len(
        classification
    ) != 136:
        fail(
            "relation_classification must contain 136 rows."
        )

    if len(
        equivalence_flags
    ) != 136:
        fail(
            "equivalence_flags must contain 136 rows."
        )

    bootstrap_replicates = (
        require_dataframe(
            context.outputs[
                "bootstrap_replicates"
            ],
            "bootstrap_replicates",
        )
    )

    if len(
        bootstrap_replicates
    ) != 68000:
        fail(
            "bootstrap_replicates must contain "
            f"68000 rows; observed "
            f"{len(bootstrap_replicates)}."
        )


def build_summary(
    context: ExperimentContext,
) -> dict[str, Any]:
    """Build the official CGIE3-ID-02 summary."""
    classification_summary = (
        require_mapping(
            context.outputs[
                "classification_summary"
            ],
            "classification_summary",
        )
    )

    interpretation_boundary = (
        require_mapping(
            context.configuration[
                "interpretation_boundary"
            ],
            "interpretation_boundary",
        )
    )

    status_counts = require_mapping(
        classification_summary[
            "status_counts"
        ],
        "classification_summary.status_counts",
    )

    return {
        "experiment_id":
            "CGIE3_ID_02",

        "experiment_name":
            "Eligible Relation Discovery",

        "engine":
            "CGIE-3",

        "framework":
            "Congruity Framework",

        "generated_at_utc":
            utc_now_iso(),

        "technical_status":
            "COMPLETED",

        "scientific_outcome":
            classification_summary[
                "scientific_outcome"
            ],

        "technical_success":
            bool(
                classification_summary[
                    "technical_success"
                ]
            ),

        "scientific_positive_result":
            bool(
                classification_summary[
                    "scientific_positive_result"
                ]
            ),

        "relation_count":
            int(
                classification_summary[
                    "relation_count"
                ]
            ),

        "status_counts": {
            str(key): int(value)
            for key, value
            in status_counts.items()
        },

        "classification_by_window":
            classification_summary[
                "by_window"
            ],

        "preprocessing":
            context.outputs[
                "preprocessing_quality_audit"
            ],

        "relation_discovery":
            context.outputs[
                "relation_discovery_summary"
            ],

        "persistence":
            context.outputs[
                "persistence_summary"
            ],

        "bootstrap":
            context.outputs[
                "bootstrap_stage_summary"
            ],

        "missingness":
            context.outputs[
                "missingness_stage_summary"
            ],

        "equivalence":
            context.outputs[
                "equivalence_summary"
            ],

        "scientific_claims": {
            "candidate_relations_evaluated":
                True,

            "eligibility_protocol_applied":
                True,

            "primary_relations_established":
                False,

            "indispensable_relations_established":
                False,

            "causality_established":
                False,

            "predictive_capability_established":
                False,

            "earthquake_prediction_established":
                False,
        },

        "interpretation_boundary":
            dict(
                interpretation_boundary
            ),

        "negative_result_is_valid":
            True,

        "claim_boundary": (
            "Eligible relations satisfy only the frozen "
            "CGIE3-ID-02 baseline eligibility protocol. "
            "Eligibility does not establish causality, "
            "indispensability, primary identity status or "
            "prediction of a specific earthquake."
        ),
    }


def markdown_table_rows(
    values: Mapping[str, Any],
) -> str:
    """Convert a mapping into Markdown table rows."""
    return "\n".join(
        f"| `{key}` | {value} |"
        for key, value
        in values.items()
    )


def build_report(
    summary: Mapping[str, Any],
    context: ExperimentContext,
) -> str:
    """Build the human-readable scientific report."""
    status_counts = require_mapping(
        summary["status_counts"],
        "summary.status_counts",
    )

    classification_by_window = (
        require_mapping(
            summary[
                "classification_by_window"
            ],
            "summary.classification_by_window",
        )
    )

    status_rows = markdown_table_rows(
        status_counts
    )

    window_sections: list[str] = []

    for window_id in sorted(
        classification_by_window
    ):
        counts = require_mapping(
            classification_by_window[
                window_id
            ],
            (
                "summary.classification_by_window."
                f"{window_id}"
            ),
        )

        rows = markdown_table_rows(
            counts
        )

        window_sections.append(
            f"""### Window `{window_id}`

| Status | Count |
|---|---:|
{rows}
"""
        )

    windows_text = "\n".join(
        window_sections
    )

    eligible_relations = (
        context.outputs[
            "relation_classification"
        ]
        .loc[
            lambda frame:
                frame[
                    "classification_status"
                ]
                == "eligible"
        ]
        .copy()
    )

    if eligible_relations.empty:
        eligible_text = (
            "No relation satisfied every frozen "
            "eligibility condition."
        )
    else:
        eligible_lines = []

        for row in eligible_relations.itertuples(
            index=False
        ):
            eligible_lines.append(
                "- "
                f"`{row.window_id}` — "
                f"`{row.source_id}` ↔ "
                f"`{row.target_id}`; "
                f"Spearman = "
                f"`{float(row.strength):.4f}`; "
                f"persistence = "
                f"`{float(row.persistence):.4f}`."
            )

        eligible_text = "\n".join(
            eligible_lines
        )

    return f"""# CGIE3-ID-02 — Eligible Relation Discovery Report

## Status

`{summary["technical_status"]}`

## Scientific outcome

`{summary["scientific_outcome"]}`

## Purpose

CGIE3-ID-02 evaluates whether relations among the frozen
Campi Flegrei seismic feature set satisfy a predetermined
baseline eligibility protocol.

The experiment does not test deterministic earthquake prediction.

## Dataset boundary

- Selection interval: frozen 2025 baseline only
- Evaluation data used for selection: `false`
- Target-event labels used for selection: `false`
- Candidate relations evaluated: `{summary["relation_count"]}`

## Overall classification

| Status | Count |
|---|---:|
{status_rows}

## Classification by temporal window

{windows_text}

## Eligible relations

{eligible_text}

## Interpretation

An `eligible` relation is one that satisfies the frozen requirements
for baseline strength, estimability, sign preservation, persistence,
bootstrap uncertainty, leave-one-block-out robustness and
missingness robustness.

Eligibility does **not** establish that a relation is:

- causal;
- indispensable;
- a primary identity relation;
- physically sufficient;
- predictive of a specific earthquake.

## Scientific claim boundary

{summary["claim_boundary"]}

## Explicit negative claims

- Primary relations established: `false`
- Indispensable relations established: `false`
- Causality established: `false`
- Predictive capability established: `false`
- Earthquake prediction established: `false`

## Reproducibility

The official output package includes:

- candidate relations;
- monthly block estimates;
- bootstrap replications;
- frozen relation classifications;
- equivalence and redundancy flags;
- summary;
- report;
- manifest.

Rejected and non-estimable relations remain preserved.

## Generated

`{summary["generated_at_utc"]}`
"""


def build_manifest(
    context: ExperimentContext,
    summary: Mapping[str, Any],
) -> dict[str, Any]:
    """Build the experiment manifest before output hashes are added."""
    experiment = require_mapping(
        context.configuration[
            "experiment"
        ],
        "experiment",
    )

    return {
        "experiment_id":
            context.experiment_id,

        "experiment_name":
            experiment.get(
                "name"
            ),

        "engine":
            experiment.get(
                "engine"
            ),

        "framework_version":
            experiment.get(
                "framework_version"
            ),

        "protocol_version":
            experiment.get(
                "protocol_version"
            ),

        "configuration_version":
            experiment.get(
                "configuration_version"
            ),

        "configuration_status":
            experiment.get(
                "status"
            ),

        "generated_at_utc":
            summary[
                "generated_at_utc"
            ],

        "identity": {
            "system_id":
                context.identity.system_id,

            "system_name":
                context.identity.system_name,

            "domain":
                context.identity.domain,

            "protocol_version":
                context.identity.protocol_version,

            "temporal_scales":
                list(
                    context.identity.temporal_scales
                ),

            "component_ids":
                list(
                    context.identity.component_ids
                ),
        },

        "loader_provenance":
            context.provenance.get(
                "loader",
                {},
            ),

        "runtime":
            context.runtime,

        "metadata":
            context.metadata,

        "scientific_outcome":
            summary[
                "scientific_outcome"
            ],

        "scientific_claims":
            summary[
                "scientific_claims"
            ],

        "software": {
            "python_version":
                platform.python_version(),

            "python_implementation":
                platform.python_implementation(),

            "platform":
                platform.platform(),

            "pandas_version":
                pd.__version__,

            "numpy_version":
                np.__version__,

            "executable":
                sys.executable,
        },

        "output_files": {
            name: str(
                path.relative_to(
                    REPOSITORY_ROOT
                )
            )
            for name, path
            in OUTPUT_PATHS.items()
        },
    }


def write_scientific_outputs(
    context: ExperimentContext,
    summary: Mapping[str, Any],
    report_text: str,
    manifest: Mapping[str, Any],
) -> dict[str, str]:
    """Write all required scientific outputs and return their hashes."""
    candidate_relations = require_dataframe(
        context.outputs[
            "candidate_relations"
        ],
        "candidate_relations",
    )

    block_relations = require_dataframe(
        context.outputs[
            "block_relations"
        ],
        "block_relations",
    )

    bootstrap_replicates = require_dataframe(
        context.outputs[
            "bootstrap_replicates"
        ],
        "bootstrap_replicates",
    )

    relation_classification = (
        require_dataframe(
            context.outputs[
                "relation_classification"
            ],
            "relation_classification",
        )
    )

    equivalence_flags = require_dataframe(
        context.outputs[
            "equivalence_flags"
        ],
        "equivalence_flags",
    )

    write_csv(
        OUTPUT_PATHS[
            "candidate_relations"
        ],
        candidate_relations,
    )

    write_csv(
        OUTPUT_PATHS[
            "block_relations"
        ],
        block_relations,
    )

    write_csv(
        OUTPUT_PATHS[
            "bootstrap_relations"
        ],
        bootstrap_replicates,
    )

    write_csv(
        OUTPUT_PATHS[
            "relation_classification"
        ],
        relation_classification,
    )

    write_csv(
        OUTPUT_PATHS[
            "equivalence_flags"
        ],
        equivalence_flags,
    )

    write_json(
        OUTPUT_PATHS[
            "summary"
        ],
        summary,
    )

    OUTPUT_PATHS[
        "report"
    ].write_text(
        report_text,
        encoding="utf-8",
    )

    write_json(
        OUTPUT_PATHS[
            "manifest"
        ],
        manifest,
    )

    output_hashes = {
        name: sha256_file(path)
        for name, path
        in OUTPUT_PATHS.items()
    }

    return output_hashes


def build_experiment_result(
    summary: Mapping[str, Any],
    output_hashes: Mapping[str, str],
    manifest: Mapping[str, Any],
) -> ExperimentResult:
    """Build the immutable experiment result object."""
    scientific_claims = require_mapping(
        summary[
            "scientific_claims"
        ],
        "summary.scientific_claims",
    )

    status = str(
        summary[
            "scientific_outcome"
        ]
    )

    return ExperimentResult(
        experiment_id="CGIE3_ID_02",

        status=status,

        summary=dict(
            summary
        ),

        outputs={
            name: {
                "path":
                    str(
                        OUTPUT_PATHS[
                            name
                        ].relative_to(
                            REPOSITORY_ROOT
                        )
                    ),

                "sha256":
                    digest,
            }
            for name, digest
            in output_hashes.items()
        },

        scientific_claims={
            str(key): bool(value)
            for key, value
            in scientific_claims.items()
        },

        statistics={
            "relation_count":
                int(
                    summary[
                        "relation_count"
                    ]
                ),

            "status_counts":
                summary[
                    "status_counts"
                ],
        },

        warnings=(
            "Eligibility does not establish "
            "causality or indispensability.",

            "CGIE3-ID-02 does not establish "
            "earthquake prediction.",
        ),

        provenance={
            "manifest":
                manifest,
        },

        metadata={
            "generated_at_utc":
                summary[
                    "generated_at_utc"
                ],
        },
    )


def generate_reports(
    context: ExperimentContext,
) -> ExperimentResult:
    """Generate all official CGIE3-ID-02 scientific outputs."""
    validate_context(
        context
    )

    validate_output_row_counts(
        context
    )

    OUTPUT_DIRECTORY.mkdir(
        parents=True,
        exist_ok=True,
    )

    summary = build_summary(
        context
    )

    report_text = build_report(
        summary,
        context,
    )

    manifest = build_manifest(
        context,
        summary,
    )

    output_hashes = (
        write_scientific_outputs(
            context,
            summary,
            report_text,
            manifest,
        )
    )

    manifest_with_hashes = dict(
        manifest
    )

    manifest_with_hashes[
        "output_sha256"
    ] = output_hashes

    write_json(
        OUTPUT_PATHS[
            "manifest"
        ],
        manifest_with_hashes,
    )

    final_hashes = dict(
        output_hashes
    )

    final_hashes[
        "manifest"
    ] = sha256_file(
        OUTPUT_PATHS[
            "manifest"
        ]
    )

    context.register_output(
        "official_summary",
        summary,
    )

    context.register_output(
        "official_manifest",
        manifest_with_hashes,
    )

    context.register_output(
        "official_output_hashes",
        final_hashes,
    )

    context.register_runtime(
        "reporting_status",
        "COMPLETED",
    )

    return build_experiment_result(
        summary=summary,
        output_hashes=final_hashes,
        manifest=manifest_with_hashes,
    )
  
  
