#!/usr/bin/env python3
"""
CF-NEG-01 — Negative-control and specificity validation engine.

This experiment does not modify CF-RETRO-01.

It evaluates whether the frozen alert episodes generated by
CF-RETRO-01 are associated with subsequent significant seismic
activity more often than expected under circularly shifted controls.

Run from the repository root:

    python cgie2/src/run_cf_negative_controls.py

Required inputs:

    cgie2/config/cf_neg_01.yaml

    outputs/CF_RETRO_01_catalog_frozen.csv
    outputs/CF_RETRO_01_catalog_frozen.csv.sha256

    outputs/CF_RETRO_01_global_alerts.csv
    outputs/CF_RETRO_01_window_alerts.csv
    outputs/CF_RETRO_01_alert_episodes.csv

    outputs/CF_RETRO_01_metrics.csv
    outputs/CF_RETRO_01_metrics.csv.sha256

Generated outputs:

    outputs/CF_NEG_01_episode_associations.csv
    outputs/CF_NEG_01_event_clusters.csv
    outputs/CF_NEG_01_random_controls.csv
    outputs/CF_NEG_01_threshold_sensitivity.csv
    outputs/CF_NEG_01_summary.json
    outputs/CF_NEG_01_report.md
    outputs/CF_NEG_01_manifest.json
"""

from __future__ import annotations

import hashlib
import json
import math
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
import yaml


SCRIPT_PATH = Path(__file__).resolve()
REPOSITORY_ROOT = SCRIPT_PATH.parents[2]

CONFIG_PATH = (
    REPOSITORY_ROOT
    / "cgie2"
    / "config"
    / "cf_neg_01.yaml"
)

LEVEL_PRIORITY = {
    "attention": 1,
    "anomaly": 2,
    "structural": 3,
}


def fail(message: str) -> None:
    """Print a fatal error and terminate execution."""
    print(f"\nERROR: {message}", file=sys.stderr)
    raise SystemExit(1)


def parse_utc(
    value: str | pd.Timestamp,
) -> pd.Timestamp:
    """Parse and normalize a timestamp to UTC."""
    try:
        timestamp = pd.Timestamp(value)
    except (TypeError, ValueError) as exc:
        raise ValueError(
            f"Invalid timestamp: {value}"
        ) from exc

    if timestamp.tzinfo is None:
        return timestamp.tz_localize("UTC")

    return timestamp.tz_convert("UTC")


def utc_string(
    value: str | pd.Timestamp,
) -> str:
    """Serialize a timestamp as ISO-8601 UTC."""
    return (
        parse_utc(value)
        .isoformat()
        .replace("+00:00", "Z")
    )


def resolve_path(
    configured_path: str,
) -> Path:
    """Resolve a repository-relative path safely."""
    resolved = (
        REPOSITORY_ROOT
        / Path(configured_path)
    ).resolve()

    try:
        resolved.relative_to(
            REPOSITORY_ROOT.resolve()
        )
    except ValueError:
        fail(
            "Configured path escapes repository root: "
            f"{configured_path}"
        )

    return resolved


def load_yaml(
    path: Path,
) -> dict[str, Any]:
    """Load a YAML mapping."""
    if not path.exists():
        fail(f"Configuration file not found: {path}")

    try:
        payload = yaml.safe_load(
            path.read_text(encoding="utf-8")
        )
    except yaml.YAMLError as exc:
        fail(f"Invalid YAML in {path}: {exc}")

    if not isinstance(payload, dict):
        fail(
            "Configuration root must be a mapping: "
            f"{path}"
        )

    return payload


def sha256_file(
    path: Path,
) -> str:
    """Calculate the SHA-256 digest of a file."""
    if not path.exists():
        fail(f"File not found for hashing: {path}")

    digest = hashlib.sha256()

    with path.open("rb") as handle:
        for block in iter(
            lambda: handle.read(1024 * 1024),
            b"",
        ):
            digest.update(block)

    return digest.hexdigest()


def read_expected_hash(
    hash_path: Path,
) -> str:
    """Read a standard SHA-256 sidecar."""
    if not hash_path.exists():
        fail(f"Hash file not found: {hash_path}")

    text = hash_path.read_text(
        encoding="utf-8"
    ).strip()

    if not text:
        fail(f"Hash file is empty: {hash_path}")

    digest = text.split()[0].lower()

    if len(digest) != 64:
        fail(
            "Invalid SHA-256 digest length in "
            f"{hash_path}"
        )

    if not set(digest).issubset(
        set("0123456789abcdef")
    ):
        fail(
            "Invalid SHA-256 characters in "
            f"{hash_path}"
        )

    return digest


def verify_hash(
    data_path: Path,
    hash_path: Path,
) -> str:
    """Verify a file against its SHA-256 sidecar."""
    expected = read_expected_hash(hash_path)
    actual = sha256_file(data_path)

    if actual != expected:
        fail(
            "SHA-256 verification failed.\n"
            f"File:     {data_path}\n"
            f"Expected: {expected}\n"
            f"Actual:   {actual}"
        )

    return actual


def get_git_commit() -> str:
    """Return the current Git commit or UNAVAILABLE."""
    try:
        result = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=REPOSITORY_ROOT,
            check=True,
            capture_output=True,
            text=True,
        )
        return result.stdout.strip()
    except (OSError, subprocess.CalledProcessError):
        return "UNAVAILABLE"


def write_json(
    path: Path,
    payload: Any,
) -> None:
    """Write deterministic JSON."""
    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    path.write_text(
        json.dumps(
            payload,
            indent=2,
            ensure_ascii=False,
            sort_keys=True,
            allow_nan=False,
        )
        + "\n",
        encoding="utf-8",
    )


def write_csv(
    path: Path,
    frame: pd.DataFrame,
    float_precision: int,
) -> None:
    """Write deterministic CSV."""
    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    output = frame.copy()

    for column in output.columns:
        if isinstance(
            output[column].dtype,
            pd.DatetimeTZDtype,
        ):
            output[column] = output[column].map(
                utc_string
            )

    output.to_csv(
        path,
        index=False,
        encoding="utf-8",
        lineterminator="\n",
        float_format=f"%.{float_precision}g",
        na_rep="",
    )


def validate_configuration(
    config: dict[str, Any],
) -> None:
    """Validate frozen CF-NEG-01 rules."""
    required_sections = {
        "experiment",
        "inputs",
        "analysis_period",
        "target_event",
        "significant_event_definition",
        "event_clustering",
        "alert_episode_definition",
        "association_windows",
        "association_rule",
        "metrics",
        "random_control",
        "primary_evaluation",
        "required_outputs",
        "reproducibility",
        "prohibited_practices",
    }

    missing = sorted(
        required_sections.difference(config)
    )

    if missing:
        fail(
            "Missing CF-NEG-01 configuration sections: "
            + ", ".join(missing)
        )

    experiment = config["experiment"]

    if experiment.get("id") != "CF_NEG_01":
        fail("Unexpected experiment identifier.")

    if experiment.get("status") != "FROZEN":
        fail("CF-NEG-01 configuration is not FROZEN.")

    if (
        config["interpretation_boundary"].get(
            "modifies_cf_retro_01"
        )
        is not False
    ):
        fail(
            "CF-NEG-01 must not modify CF-RETRO-01."
        )

    if (
        config["interpretation_boundary"].get(
            "permits_threshold_tuning"
        )
        is not False
    ):
        fail(
            "CF-NEG-01 must prohibit threshold tuning."
        )

    start = parse_utc(
        config["analysis_period"]["start_utc"]
    )

    end = parse_utc(
        config["analysis_period"]["end_utc"]
    )

    target = parse_utc(
        config["target_event"]["utc_time"]
    )

    if start >= end:
        fail("Invalid CF-NEG-01 analysis interval.")

    if end >= target:
        fail(
            "Analysis period must end before target event."
        )

    primary_window = config[
        "association_windows"
    ]["primary"]

    if (
        float(
            primary_window["maximum_lead_hours"]
        )
        != 168.0
    ):
        fail(
            "Frozen primary association window "
            "must equal 168 hours."
        )

    if (
        float(
            config[
                "significant_event_definition"
            ]["minimum_magnitude"]
        )
        != 3.0
    ):
        fail(
            "Frozen primary magnitude threshold "
            "must equal 3.0."
        )

    random_control = config["random_control"]

    if int(
        random_control["repetitions"]
    ) != 1000:
        fail(
            "Frozen random-control repetitions "
            "must equal 1000."
        )

    if (
        random_control["method"]
        != "circular_time_shift"
    ):
        fail(
            "Unsupported random-control method."
        )

    if (
        random_control.get(
            "preserve_episode_durations"
        )
        is not True
    ):
        fail(
            "Random controls must preserve "
            "episode durations."
        )

    if (
        random_control.get(
            "preserve_interepisode_structure"
        )
        is not True
    ):
        fail(
            "Random controls must preserve "
            "interepisode structure."
        )


def load_catalogue(
    config: dict[str, Any],
) -> tuple[pd.DataFrame, str]:
    """Load and verify the frozen earthquake catalogue."""
    catalogue_config = config[
        "inputs"
    ]["frozen_catalogue"]

    catalogue_path = resolve_path(
        catalogue_config["file"]
    )

    hash_path = resolve_path(
        catalogue_config["hash_file"]
    )

    catalogue_hash = verify_hash(
        catalogue_path,
        hash_path,
    )

    catalogue = pd.read_csv(
        catalogue_path,
        encoding="utf-8",
    )

    if catalogue.empty:
        fail("Frozen catalogue is empty.")

    required_columns = {
        "event_id",
        "time_utc",
        "magnitude",
        "latitude",
        "longitude",
        "depth_km",
    }

    missing = sorted(
        required_columns.difference(
            catalogue.columns
        )
    )

    if missing:
        fail(
            "Catalogue is missing required columns: "
            + ", ".join(missing)
        )

    catalogue["time_utc"] = pd.to_datetime(
        catalogue["time_utc"],
        utc=True,
        errors="coerce",
        format="mixed",
    )

    catalogue["magnitude"] = pd.to_numeric(
        catalogue["magnitude"],
        errors="coerce",
    )

    catalogue["depth_km"] = pd.to_numeric(
        catalogue["depth_km"],
        errors="coerce",
    )

    if catalogue["time_utc"].isna().any():
        fail(
            "Catalogue contains invalid timestamps."
        )

    if catalogue["magnitude"].isna().any():
        fail(
            "Catalogue contains invalid magnitudes."
        )

    if catalogue["event_id"].duplicated().any():
        fail(
            "Catalogue contains duplicate event IDs."
        )

    analysis_start = parse_utc(
        config["analysis_period"]["start_utc"]
    )

    analysis_end = parse_utc(
        config["analysis_period"]["end_utc"]
    )

    target_event = parse_utc(
        config["target_event"]["utc_time"]
    )

    catalogue = catalogue.loc[
        (
            catalogue["time_utc"]
            >= analysis_start
        )
        & (
            catalogue["time_utc"]
            <= analysis_end
        )
    ].copy()

    if catalogue.empty:
        fail(
            "No catalogue events remain inside "
            "the analysis period."
        )

    if (
        catalogue["time_utc"]
        >= target_event
    ).any():
        fail(
            "Target-event or later observations "
            "entered CF-NEG-01."
        )

    return (
        catalogue.sort_values(
            by=["time_utc", "event_id"],
            kind="stable",
        ).reset_index(drop=True),
        catalogue_hash,
    )


def load_alert_episodes(
    config: dict[str, Any],
) -> pd.DataFrame:
    """Load frozen CF-RETRO-01 alert episodes."""
    path = resolve_path(
        config["inputs"][
            "alert_episodes"
        ]["file"]
    )

    if not path.exists():
        fail(
            "Alert-episode file not found: "
            f"{path}"
        )

    episodes = pd.read_csv(
        path,
        encoding="utf-8",
    )

    required_columns = {
        "episode_id",
        "start_utc",
        "end_utc",
        "duration_hours",
        "maximum_level",
    }

    missing = sorted(
        required_columns.difference(
            episodes.columns
        )
    )

    if missing:
        fail(
            "Alert episodes are missing columns: "
            + ", ".join(missing)
        )

    episodes["start_utc"] = pd.to_datetime(
        episodes["start_utc"],
        utc=True,
        errors="coerce",
        format="mixed",
    )

    episodes["end_utc"] = pd.to_datetime(
        episodes["end_utc"],
        utc=True,
        errors="coerce",
        format="mixed",
    )

    episodes["duration_hours"] = pd.to_numeric(
        episodes["duration_hours"],
        errors="coerce",
    )

    if (
        episodes["start_utc"].isna().any()
        or episodes["end_utc"].isna().any()
    ):
        fail(
            "Alert episodes contain invalid timestamps."
        )

    if episodes["duration_hours"].isna().any():
        fail(
            "Alert episodes contain invalid durations."
        )

    valid_levels = set(
        config[
            "alert_episode_definition"
        ]["included_levels"]
    )

    observed_levels = set(
        episodes["maximum_level"]
        .astype(str)
        .unique()
    )

    if not observed_levels.issubset(
        valid_levels
    ):
        fail(
            "Alert episodes contain unsupported levels: "
            + repr(observed_levels)
        )

    analysis_start = parse_utc(
        config["analysis_period"]["start_utc"]
    )

    analysis_end = parse_utc(
        config["analysis_period"]["end_utc"]
    )

    episodes = episodes.loc[
        (
            episodes["start_utc"]
            >= analysis_start
        )
        & (
            episodes["start_utc"]
            <= analysis_end
        )
    ].copy()

    episodes = episodes.sort_values(
        by=["start_utc", "episode_id"],
        kind="stable",
    ).reset_index(drop=True)

    return episodes


def validate_supporting_inputs(
    config: dict[str, Any],
) -> dict[str, str]:
    """
    Verify metrics and confirm that other frozen outputs exist.

    The global and window alert tables are not altered or recomputed.
    """
    hashes: dict[str, str] = {}

    metrics_config = config["inputs"]["metrics"]

    metrics_path = resolve_path(
        metrics_config["file"]
    )

    metrics_hash_path = resolve_path(
        metrics_config["hash_file"]
    )

    hashes["metrics_sha256"] = verify_hash(
        metrics_path,
        metrics_hash_path,
    )

    for key in [
        "global_alerts",
        "window_alerts",
    ]:
        path = resolve_path(
            config["inputs"][key]["file"]
        )

        if not path.exists() or path.stat().st_size == 0:
            fail(
                f"Required frozen input is absent or empty: {path}"
            )

        hashes[f"{key}_sha256"] = (
            sha256_file(path)
        )

    episodes_path = resolve_path(
        config["inputs"][
            "alert_episodes"
        ]["file"]
    )

    hashes["alert_episodes_sha256"] = (
        sha256_file(episodes_path)
    )

    return hashes


def cluster_significant_events(
    catalogue: pd.DataFrame,
    magnitude_threshold: float,
    cluster_gap_hours: float,
) -> pd.DataFrame:
    """
    Select significant events and temporally cluster them.

    A new cluster begins when the gap from the previous significant
    event exceeds the frozen cluster gap.
    """
    significant = catalogue.loc[
        catalogue["magnitude"]
        >= magnitude_threshold
    ].copy()

    output_columns = [
        "cluster_id",
        "cluster_start_utc",
        "cluster_end_utc",
        "representative_event_id",
        "representative_event_time_utc",
        "representative_magnitude",
        "representative_depth_km",
        "event_count",
        "member_event_ids",
    ]

    if significant.empty:
        return pd.DataFrame(
            columns=output_columns
        )

    significant = significant.sort_values(
        by=["time_utc", "event_id"],
        kind="stable",
    ).reset_index(drop=True)

    time_gaps = (
        significant["time_utc"]
        .diff()
        .dt.total_seconds()
        .div(3600.0)
    )

    new_cluster = (
        time_gaps.isna()
        | (
            time_gaps
            > cluster_gap_hours
        )
    )

    significant["_cluster_id"] = (
        new_cluster.cumsum().astype(int)
    )

    records: list[dict[str, Any]] = []

    for cluster_number, group in (
        significant.groupby(
            "_cluster_id",
            sort=True,
        )
    ):
        maximum_magnitude = float(
            group["magnitude"].max()
        )

        representative_candidates = group.loc[
            group["magnitude"]
            == maximum_magnitude
        ].sort_values(
            by=["time_utc", "event_id"],
            kind="stable",
        )

        representative = (
            representative_candidates.iloc[0]
        )

        records.append(
            {
                "cluster_id":
                    int(cluster_number),
                "cluster_start_utc":
                    utc_string(
                        group["time_utc"].min()
                    ),
                "cluster_end_utc":
                    utc_string(
                        group["time_utc"].max()
                    ),
                "representative_event_id":
                    str(
                        representative["event_id"]
                    ),
                "representative_event_time_utc":
                    utc_string(
                        representative["time_utc"]
                    ),
                "representative_magnitude":
                    maximum_magnitude,
                "representative_depth_km":
                    (
                        float(
                            representative["depth_km"]
                        )
                        if pd.notna(
                            representative["depth_km"]
                        )
                        else math.nan
                    ),
                "event_count":
                    int(len(group)),
                "member_event_ids":
                    ",".join(
                        group["event_id"]
                        .astype(str)
                        .tolist()
                    ),
            }
        )

    return pd.DataFrame.from_records(
        records,
        columns=output_columns,
    )


def associate_episodes(
    episodes: pd.DataFrame,
    event_clusters: pd.DataFrame,
    maximum_lead_hours: float,
    primary_levels: set[str],
) -> pd.DataFrame:
    """
    Associate each episode with the first subsequent event cluster.

    An event is associated when its representative time occurs at or
    after the episode start and no later than the frozen lead horizon.
    """
    records: list[dict[str, Any]] = []

    if event_clusters.empty:
        event_times = pd.Series(
            dtype="datetime64[ns, UTC]"
        )
    else:
        event_times = pd.to_datetime(
            event_clusters[
                "representative_event_time_utc"
            ],
            utc=True,
            errors="raise",
            format="mixed",
        )

    for episode in episodes.itertuples(
        index=False
    ):
        start = parse_utc(
            episode.start_utc
        )

        end = parse_utc(
            episode.end_utc
        )

        association_end = (
            start
            + pd.Timedelta(
                hours=maximum_lead_hours
            )
        )

        if event_clusters.empty:
            candidates = (
                event_clusters.copy()
            )
        else:
            candidate_mask = (
                (event_times >= start)
                & (
                    event_times
                    <= association_end
                )
            )

            candidates = event_clusters.loc[
                candidate_mask
            ].copy()

        associated = not candidates.empty

        if associated:
            candidates[
                "_representative_time"
            ] = pd.to_datetime(
                candidates[
                    "representative_event_time_utc"
                ],
                utc=True,
                errors="raise",
                format="mixed",
            )

            candidates = candidates.sort_values(
                by=[
                    "_representative_time",
                    "cluster_id",
                ],
                kind="stable",
            )

            first_event = candidates.iloc[0]

            event_time = parse_utc(
                first_event[
                    "representative_event_time_utc"
                ]
            )

            lead_hours = (
                event_time - start
            ).total_seconds() / 3600.0

            overlapping = (
                event_time <= end
            )

            classification = (
                "overlapping"
                if overlapping
                else "associated"
            )

            cluster_id: int | None = int(
                first_event["cluster_id"]
            )

            representative_event_id = str(
                first_event[
                    "representative_event_id"
                ]
            )

            representative_magnitude = float(
                first_event[
                    "representative_magnitude"
                ]
            )

            associated_cluster_count = int(
                len(candidates)
            )

        else:
            later_candidates = (
                event_clusters.copy()
            )

            if not later_candidates.empty:
                later_candidates[
                    "_representative_time"
                ] = pd.to_datetime(
                    later_candidates[
                        "representative_event_time_utc"
                    ],
                    utc=True,
                    errors="raise",
                    format="mixed",
                )

                later_candidates = (
                    later_candidates.loc[
                        later_candidates[
                            "_representative_time"
                        ]
                        > association_end
                    ]
                    .sort_values(
                        by=[
                            "_representative_time",
                            "cluster_id",
                        ],
                        kind="stable",
                    )
                )

            if not later_candidates.empty:
                first_later = (
                    later_candidates.iloc[0]
                )

                event_time = parse_utc(
                    first_later[
                        "representative_event_time_utc"
                    ]
                )

                lead_hours = (
                    event_time - start
                ).total_seconds() / 3600.0

                classification = "remote"

                cluster_id = int(
                    first_later["cluster_id"]
                )

                representative_event_id = str(
                    first_later[
                        "representative_event_id"
                    ]
                )

                representative_magnitude = float(
                    first_later[
                        "representative_magnitude"
                    ]
                )

            else:
                event_time = None
                lead_hours = math.nan
                classification = "unassociated"
                cluster_id = None
                representative_event_id = ""
                representative_magnitude = (
                    math.nan
                )

            overlapping = False
            associated_cluster_count = 0

        maximum_level = str(
            episode.maximum_level
        )

        records.append(
            {
                "episode_id":
                    int(episode.episode_id),
                "episode_start_utc":
                    utc_string(start),
                "episode_end_utc":
                    utc_string(end),
                "episode_duration_hours":
                    float(
                        episode.duration_hours
                    ),
                "maximum_level":
                    maximum_level,
                "is_primary_episode":
                    maximum_level
                    in primary_levels,
                "association_window_hours":
                    float(
                        maximum_lead_hours
                    ),
                "associated":
                    associated,
                "classification":
                    classification,
                "overlapping_event":
                    overlapping,
                "associated_cluster_count":
                    associated_cluster_count,
                "first_event_cluster_id":
                    cluster_id,
                "first_event_id":
                    representative_event_id,
                "first_event_time_utc":
                    (
                        utc_string(event_time)
                        if event_time is not None
                        else ""
                    ),
                "first_event_magnitude":
                    representative_magnitude,
                "lead_time_hours":
                    lead_hours,
            }
        )

    return pd.DataFrame.from_records(
        records
    )


def event_detection_metrics(
    associations: pd.DataFrame,
    event_clusters: pd.DataFrame,
    episodes: pd.DataFrame,
    maximum_lead_hours: float,
) -> dict[str, Any]:
    """
    Determine how many event clusters were preceded by an alert episode.
    """
    if event_clusters.empty:
        return {
            "event_cluster_count": 0,
            "event_clusters_preceded_by_alert": 0,
            "event_detection_fraction": 0.0,
        }

    episode_starts = pd.to_datetime(
        episodes["start_utc"],
        utc=True,
        errors="raise",
        format="mixed",
    )

    detected_count = 0

    for event in event_clusters.itertuples(
        index=False
    ):
        event_time = parse_utc(
            event.representative_event_time_utc
        )

        earliest_allowed = (
            event_time
            - pd.Timedelta(
                hours=maximum_lead_hours
            )
        )

        preceded = (
            (
                episode_starts
                >= earliest_allowed
            )
            & (
                episode_starts
                <= event_time
            )
        ).any()

        if preceded:
            detected_count += 1

    event_count = int(
        len(event_clusters)
    )

    return {
        "event_cluster_count":
            event_count,
        "event_clusters_preceded_by_alert":
            int(detected_count),
        "event_detection_fraction":
            (
                float(
                    detected_count
                    / event_count
                )
                if event_count > 0
                else 0.0
            ),
    }


def summarize_associations(
    associations: pd.DataFrame,
    event_clusters: pd.DataFrame,
    episodes: pd.DataFrame,
    maximum_lead_hours: float,
    analysis_duration_hours: float,
) -> dict[str, Any]:
    """Calculate frozen specificity metrics."""
    episode_count = int(
        len(associations)
    )

    if episode_count == 0:
        associated_count = 0
        unassociated_count = 0
        precision = 0.0
        false_discovery_fraction = 0.0
    else:
        associated_count = int(
            associations["associated"].sum()
        )

        unassociated_count = (
            episode_count
            - associated_count
        )

        precision = float(
            associated_count
            / episode_count
        )

        false_discovery_fraction = float(
            unassociated_count
            / episode_count
        )

    associated_leads = pd.to_numeric(
        associations.loc[
            associations["associated"],
            "lead_time_hours",
        ],
        errors="coerce",
    ).dropna()

    episode_durations = pd.to_numeric(
        associations[
            "episode_duration_hours"
        ],
        errors="coerce",
    ).dropna()

    alert_duration_hours = float(
        episode_durations.sum()
    )

    alert_time_fraction = (
        alert_duration_hours
        / analysis_duration_hours
        if analysis_duration_hours > 0.0
        else 0.0
    )

    event_metrics = event_detection_metrics(
        associations=associations,
        event_clusters=event_clusters,
        episodes=episodes,
        maximum_lead_hours=(
            maximum_lead_hours
        ),
    )

    def distribution_summary(
        values: pd.Series,
    ) -> dict[str, float | None]:
        if values.empty:
            return {
                "minimum_hours": None,
                "median_hours": None,
                "mean_hours": None,
                "maximum_hours": None,
            }

        return {
            "minimum_hours":
                float(values.min()),
            "median_hours":
                float(values.median()),
            "mean_hours":
                float(values.mean()),
            "maximum_hours":
                float(values.max()),
        }

    return {
        "alert_episode_count":
            episode_count,
        "associated_episode_count":
            associated_count,
        "unassociated_episode_count":
            unassociated_count,
        "associated_episode_fraction":
            precision,
        "precision":
            precision,
        "false_discovery_fraction":
            false_discovery_fraction,
        "alert_duration_hours":
            alert_duration_hours,
        "alert_time_fraction":
            float(alert_time_fraction),
        "lead_time":
            distribution_summary(
                associated_leads
            ),
        "episode_duration":
            distribution_summary(
                episode_durations
            ),
        **event_metrics,
    }


def circular_shift_episodes(
    episodes: pd.DataFrame,
    shift_hours: int,
    period_start: pd.Timestamp,
    period_end: pd.Timestamp,
) -> pd.DataFrame:
    """
    Shift the complete episode sequence circularly.

    The same temporal displacement is applied to all episode starts,
    preserving interepisode structure. Episode durations are unchanged.
    """
    period_hours = int(
        (
            period_end - period_start
        ).total_seconds()
        // 3600
    ) + 1

    if period_hours <= 0:
        fail(
            "Invalid circular-shift period."
        )

    shifted = episodes.copy()

    original_starts = pd.to_datetime(
        shifted["start_utc"],
        utc=True,
        errors="raise",
        format="mixed",
    )

    durations = pd.to_numeric(
        shifted["duration_hours"],
        errors="raise",
    )

    offsets_hours = (
        (
            original_starts - period_start
        ).dt.total_seconds()
        .div(3600.0)
        .round()
        .astype(int)
    )

    shifted_offsets = (
        offsets_hours + shift_hours
    ) % period_hours

    shifted_starts = (
        period_start
        + pd.to_timedelta(
            shifted_offsets,
            unit="h",
        )
    )

    shifted_ends = (
        shifted_starts
        + pd.to_timedelta(
            durations,
            unit="h",
        )
    )

    shifted["start_utc"] = shifted_starts
    shifted["end_utc"] = shifted_ends

    return shifted.sort_values(
        by=["start_utc", "episode_id"],
        kind="stable",
    ).reset_index(drop=True)


def run_random_controls(
    episodes: pd.DataFrame,
    event_clusters: pd.DataFrame,
    config: dict[str, Any],
    observed_associated_count: int,
) -> tuple[
    pd.DataFrame,
    dict[str, Any],
]:
    """Execute deterministic circular time-shift controls."""
    random_config = config[
        "random_control"
    ]

    repetitions = int(
        random_config["repetitions"]
    )

    seed = int(
        random_config["random_seed"]
    )

    minimum_shift_hours = int(
        random_config[
            "minimum_shift_hours"
        ]
    )

    period_start = parse_utc(
        config["analysis_period"][
            "start_utc"
        ]
    )

    period_end = parse_utc(
        config["analysis_period"][
            "end_utc"
        ]
    )

    period_hours = int(
        (
            period_end - period_start
        ).total_seconds()
        // 3600
    ) + 1

    if (
        2 * minimum_shift_hours
        >= period_hours
    ):
        fail(
            "Minimum circular shift is too large "
            "for the analysis period."
        )

    allowed_shifts = np.arange(
        minimum_shift_hours,
        period_hours - minimum_shift_hours,
        dtype=int,
    )

    if len(allowed_shifts) == 0:
        fail(
            "No admissible circular shifts remain."
        )

    rng = np.random.default_rng(seed)

    sampled_shifts = rng.choice(
        allowed_shifts,
        size=repetitions,
        replace=True,
    )

    primary_window_hours = float(
        config["association_windows"][
            "primary"
        ]["maximum_lead_hours"]
    )

    primary_levels = set(
        config[
            "alert_episode_definition"
        ]["primary_episode_levels"]
    )

    records: list[dict[str, Any]] = []

    for repetition_index, shift_hours in enumerate(
        sampled_shifts,
        start=1,
    ):
        shifted_episodes = (
            circular_shift_episodes(
                episodes=episodes,
                shift_hours=int(
                    shift_hours
                ),
                period_start=period_start,
                period_end=period_end,
            )
        )

        associations = associate_episodes(
            episodes=shifted_episodes,
            event_clusters=event_clusters,
            maximum_lead_hours=(
                primary_window_hours
            ),
            primary_levels=primary_levels,
        )

        associated_count = int(
            associations[
                "associated"
            ].sum()
        )

        episode_count = int(
            len(associations)
        )

        associated_fraction = (
            float(
                associated_count
                / episode_count
            )
            if episode_count > 0
            else 0.0
        )

        records.append(
            {
                "repetition":
                    repetition_index,
                "shift_hours":
                    int(shift_hours),
                "associated_episode_count":
                    associated_count,
                "associated_episode_fraction":
                    associated_fraction,
            }
        )

        if (
            repetition_index % 100 == 0
            or repetition_index
            == repetitions
        ):
            print(
                "Random controls completed: "
                f"{repetition_index}/"
                f"{repetitions}"
            )

    controls = pd.DataFrame.from_records(
        records
    )

    greater_or_equal_count = int(
        (
            controls[
                "associated_episode_count"
            ]
            >= observed_associated_count
        ).sum()
    )

    empirical_p_value = float(
        (
            1
            + greater_or_equal_count
        )
        / (
            1
            + repetitions
        )
    )

    random_summary = {
        "repetitions":
            repetitions,
        "random_seed":
            seed,
        "observed_associated_episode_count":
            int(
                observed_associated_count
            ),
        "random_associated_count_minimum":
            int(
                controls[
                    "associated_episode_count"
                ].min()
            ),
        "random_associated_count_median":
            float(
                controls[
                    "associated_episode_count"
                ].median()
            ),
        "random_associated_count_mean":
            float(
                controls[
                    "associated_episode_count"
                ].mean()
            ),
        "random_associated_count_maximum":
            int(
                controls[
                    "associated_episode_count"
                ].max()
            ),
        "random_associated_fraction_median":
            float(
                controls[
                    "associated_episode_fraction"
                ].median()
            ),
        "random_associated_fraction_mean":
            float(
                controls[
                    "associated_episode_fraction"
                ].mean()
            ),
        "random_greater_than_or_equal_count":
            greater_or_equal_count,
        "empirical_p_value":
            empirical_p_value,
    }

    return controls, random_summary


def build_sensitivity_table(
    catalogue: pd.DataFrame,
    episodes: pd.DataFrame,
    config: dict[str, Any],
    analysis_duration_hours: float,
) -> pd.DataFrame:
    """Evaluate frozen secondary magnitude and lead windows."""
    primary_threshold = float(
        config[
            "significant_event_definition"
        ]["minimum_magnitude"]
    )

    secondary_thresholds = [
        float(value)
        for value in config[
            "significant_event_definition"
        ].get(
            "secondary_thresholds",
            [],
        )
    ]

    magnitude_thresholds = (
        [primary_threshold]
        + secondary_thresholds
    )

    association_windows = [
        {
            "id": "primary_7d",
            "maximum_lead_hours": float(
                config[
                    "association_windows"
                ]["primary"][
                    "maximum_lead_hours"
                ]
            ),
        }
    ]

    association_windows.extend(
        config[
            "association_windows"
        ].get(
            "secondary",
            [],
        )
    )

    cluster_gap_hours = float(
        config["event_clustering"][
            "cluster_gap_hours"
        ]
    )

    primary_levels = set(
        config[
            "alert_episode_definition"
        ]["primary_episode_levels"]
    )

    records: list[dict[str, Any]] = []

    for magnitude_threshold in (
        magnitude_thresholds
    ):
        event_clusters = (
            cluster_significant_events(
                catalogue=catalogue,
                magnitude_threshold=(
                    magnitude_threshold
                ),
                cluster_gap_hours=(
                    cluster_gap_hours
                ),
            )
        )

        for window in association_windows:
            window_id = str(
                window["id"]
            )

            maximum_lead_hours = float(
                window[
                    "maximum_lead_hours"
                ]
            )

            associations = associate_episodes(
                episodes=episodes,
                event_clusters=event_clusters,
                maximum_lead_hours=(
                    maximum_lead_hours
                ),
                primary_levels=primary_levels,
            )

            metrics = summarize_associations(
                associations=associations,
                event_clusters=event_clusters,
                episodes=episodes,
                maximum_lead_hours=(
                    maximum_lead_hours
                ),
                analysis_duration_hours=(
                    analysis_duration_hours
                ),
            )

            records.append(
                {
                    "magnitude_threshold":
                        magnitude_threshold,
                    "association_window_id":
                        window_id,
                    "association_window_hours":
                        maximum_lead_hours,
                    "event_cluster_count":
                        metrics[
                            "event_cluster_count"
                        ],
                    "associated_episode_count":
                        metrics[
                            "associated_episode_count"
                        ],
                    "unassociated_episode_count":
                        metrics[
                            "unassociated_episode_count"
                        ],
                    "associated_episode_fraction":
                        metrics[
                            "associated_episode_fraction"
                        ],
                    "event_detection_fraction":
                        metrics[
                            "event_detection_fraction"
                        ],
                    "false_discovery_fraction":
                        metrics[
                            "false_discovery_fraction"
                        ],
                }
            )

    return pd.DataFrame.from_records(
        records
    )


def classify_evidence(
    observed: dict[str, Any],
    random_summary: dict[str, Any],
) -> str:
    """Apply frozen CF-NEG-01 evidence classes."""
    observed_fraction = float(
        observed[
            "associated_episode_fraction"
        ]
    )

    random_median = float(
        random_summary[
            "random_associated_fraction_median"
        ]
    )

    empirical_p_value = float(
        random_summary[
            "empirical_p_value"
        ]
    )

    false_discovery_fraction = float(
        observed[
            "false_discovery_fraction"
        ]
    )

    if (
        empirical_p_value < 0.05
        and observed_fraction
        > random_median
        and false_discovery_fraction
        < 0.50
    ):
        return "specific"

    if (
        observed_fraction
        <= random_median
    ):
        return "non_discriminating"

    if false_discovery_fraction >= 0.50:
        return "excessive_false_positives"

    return "preliminary"


def write_report(
    path: Path,
    summary: dict[str, Any],
) -> None:
    """Write the human-readable CF-NEG-01 report."""
    observed = summary[
        "primary_observed_metrics"
    ]

    random_summary = summary[
        "random_control"
    ]

    report = f"""# CF-NEG-01 — Specificity and Negative-Control Report

## Scientific status

Experiment: CF-NEG-01

Configuration status: FROZEN

Analysis type: retrospective negative-control and specificity validation

Earthquake-prediction claim: no

## Primary analysis

Magnitude threshold:

{summary["primary_magnitude_threshold"]:.1f}

Post-alert association window:

{summary["primary_association_window_hours"]:.0f} hours

Alert episodes:

{observed["alert_episode_count"]}

Significant event clusters:

{observed["event_cluster_count"]}

Associated alert episodes:

{observed["associated_episode_count"]}

Unassociated alert episodes:

{observed["unassociated_episode_count"]}

Associated episode fraction:

{observed["associated_episode_fraction"]:.6f}

False-discovery fraction:

{observed["false_discovery_fraction"]:.6f}

Event-detection fraction:

{observed["event_detection_fraction"]:.6f}

Alert-time fraction:

{observed["alert_time_fraction"]:.6f}

## Circular time-shift controls

Repetitions:

{random_summary["repetitions"]}

Observed associated episode count:

{random_summary["observed_associated_episode_count"]}

Random median associated episode count:

{random_summary["random_associated_count_median"]:.3f}

Random mean associated episode count:

{random_summary["random_associated_count_mean"]:.3f}

Empirical p-value:

{random_summary["empirical_p_value"]:.6f}

## Evidence classification

{summary["evidence_class"]}

## Interpretation boundary

CF-NEG-01 tests whether frozen CF-RETRO-01 alerts are more strongly
associated with subsequent significant seismic activity than circularly
shifted versions of the same alert sequence.

A specific or preliminary association does not demonstrate deterministic
earthquake prediction.

A non-discriminating or excessive-false-positive result must be retained
as a limitation or falsification of the current alert formulation.
"""

    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    path.write_text(
        report,
        encoding="utf-8",
    )


def main() -> None:
    print("=" * 78)
    print("CF-NEG-01 — SPECIFICITY AND NEGATIVE CONTROLS")
    print("=" * 78)

    config = load_yaml(CONFIG_PATH)

    validate_configuration(config)

    configuration_hash = sha256_file(
        CONFIG_PATH
    )

    catalogue, catalogue_hash = (
        load_catalogue(config)
    )

    episodes = load_alert_episodes(
        config
    )

    supporting_hashes = (
        validate_supporting_inputs(config)
    )

    analysis_start = parse_utc(
        config["analysis_period"]["start_utc"]
    )

    analysis_end = parse_utc(
        config["analysis_period"]["end_utc"]
    )

    analysis_duration_hours = float(
        (
            analysis_end - analysis_start
        ).total_seconds()
        / 3600.0
    )

    primary_magnitude_threshold = float(
        config[
            "significant_event_definition"
        ]["minimum_magnitude"]
    )

    cluster_gap_hours = float(
        config[
            "event_clustering"
        ]["cluster_gap_hours"]
    )

    primary_association_hours = float(
        config[
            "association_windows"
        ]["primary"][
            "maximum_lead_hours"
        ]
    )

    primary_levels = set(
        config[
            "alert_episode_definition"
        ]["primary_episode_levels"]
    )

    print(f"Catalogue rows: {len(catalogue)}")
    print(f"Alert episodes: {len(episodes)}")
    print(
        "Primary magnitude threshold: "
        f"{primary_magnitude_threshold:.1f}"
    )
    print(
        "Primary association window: "
        f"{primary_association_hours:.0f} hours"
    )
    print()

    event_clusters = (
        cluster_significant_events(
            catalogue=catalogue,
            magnitude_threshold=(
                primary_magnitude_threshold
            ),
            cluster_gap_hours=(
                cluster_gap_hours
            ),
        )
    )

    episode_associations = (
        associate_episodes(
            episodes=episodes,
            event_clusters=event_clusters,
            maximum_lead_hours=(
                primary_association_hours
            ),
            primary_levels=primary_levels,
        )
    )

    primary_metrics = (
        summarize_associations(
            associations=episode_associations,
            event_clusters=event_clusters,
            episodes=episodes,
            maximum_lead_hours=(
                primary_association_hours
            ),
            analysis_duration_hours=(
                analysis_duration_hours
            ),
        )
    )

    random_controls, random_summary = (
        run_random_controls(
            episodes=episodes,
            event_clusters=event_clusters,
            config=config,
            observed_associated_count=int(
                primary_metrics[
                    "associated_episode_count"
                ]
            ),
        )
    )

    sensitivity = build_sensitivity_table(
        catalogue=catalogue,
        episodes=episodes,
        config=config,
        analysis_duration_hours=(
            analysis_duration_hours
        ),
    )

    evidence_class = classify_evidence(
        observed=primary_metrics,
        random_summary=random_summary,
    )

    outputs = config[
        "required_outputs"
    ]

    episode_associations_path = (
        resolve_path(
            outputs[
                "episode_associations"
            ]["file"]
        )
    )

    event_clusters_path = resolve_path(
        outputs["event_clusters"]["file"]
    )

    random_controls_path = resolve_path(
        outputs["random_controls"]["file"]
    )

    sensitivity_path = resolve_path(
        outputs[
            "threshold_sensitivity"
        ]["file"]
    )

    summary_path = resolve_path(
        outputs["summary"]["file"]
    )

    report_path = resolve_path(
        outputs["report"]["file"]
    )

    manifest_path = resolve_path(
        outputs["manifest"]["file"]
    )

    float_precision = int(
        config[
            "reproducibility"
        ]["float_precision"]
    )

    write_csv(
        episode_associations_path,
        episode_associations,
        float_precision,
    )

    write_csv(
        event_clusters_path,
        event_clusters,
        float_precision,
    )

    write_csv(
        random_controls_path,
        random_controls,
        float_precision,
    )

    write_csv(
        sensitivity_path,
        sensitivity,
        float_precision,
    )

    summary = {
        "experiment_id":
            "CF_NEG_01",
        "configuration_version":
            config["experiment"]["version"],
        "analysis_start_utc":
            utc_string(analysis_start),
        "analysis_end_utc":
            utc_string(analysis_end),
        "target_event_utc":
            config[
                "target_event"
            ]["utc_time"],
        "target_event_included":
            False,
        "primary_magnitude_threshold":
            primary_magnitude_threshold,
        "primary_association_window_hours":
            primary_association_hours,
        "primary_observed_metrics":
            primary_metrics,
        "random_control":
            random_summary,
        "evidence_class":
            evidence_class,
        "earthquake_prediction_claim":
            False,
        "interpretation":
            (
                "Retrospective alert specificity "
                "and negative-control evaluation only."
            ),
    }

    write_json(
        summary_path,
        summary,
    )

    write_report(
        report_path,
        summary,
    )

    manifest = {
        "experiment_id":
            "CF_NEG_01",
        "stage":
            "negative_control_and_specificity",
        "configuration_status":
            config[
                "experiment"
            ]["status"],
        "execution_timestamp_utc":
            datetime.now(
                timezone.utc
            )
            .isoformat()
            .replace("+00:00", "Z"),
        "source_commit":
            get_git_commit(),
        "configuration_file":
            str(
                CONFIG_PATH.relative_to(
                    REPOSITORY_ROOT
                )
            ),
        "configuration_sha256":
            configuration_hash,
        "script_sha256":
            sha256_file(SCRIPT_PATH),
        "input_hashes": {
            "catalogue_sha256":
                catalogue_hash,
            **supporting_hashes,
        },
        "output_hashes": {
            "episode_associations_sha256":
                sha256_file(
                    episode_associations_path
                ),
            "event_clusters_sha256":
                sha256_file(
                    event_clusters_path
                ),
            "random_controls_sha256":
                sha256_file(
                    random_controls_path
                ),
            "threshold_sensitivity_sha256":
                sha256_file(
                    sensitivity_path
                ),
            "summary_sha256":
                sha256_file(
                    summary_path
                ),
            "report_sha256":
                sha256_file(
                    report_path
                ),
        },
        "catalogue_rows":
            int(len(catalogue)),
        "alert_episode_count":
            int(len(episodes)),
        "event_cluster_count":
            int(len(event_clusters)),
        "random_control_repetitions":
            int(
                config[
                    "random_control"
                ]["repetitions"]
            ),
        "random_seed":
            int(
                config[
                    "random_control"
                ]["random_seed"]
            ),
        "target_event_included":
            False,
        "post_cutoff_data_used":
            False,
        "cf_retro_01_modified":
            False,
        "summary":
            summary,
    }

    write_json(
        manifest_path,
        manifest,
    )

    print()
    print("=" * 78)
    print("CF-NEG-01 COMPLETED")
    print("=" * 78)
    print(
        "Significant event clusters: "
        f"{primary_metrics['event_cluster_count']}"
    )
    print(
        "Associated alert episodes: "
        f"{primary_metrics['associated_episode_count']}"
    )
    print(
        "Unassociated alert episodes: "
        f"{primary_metrics['unassociated_episode_count']}"
    )
    print(
        "Associated episode fraction: "
        f"{primary_metrics['associated_episode_fraction']:.6f}"
    )
    print(
        "False-discovery fraction: "
        f"{primary_metrics['false_discovery_fraction']:.6f}"
    )
    print(
        "Event-detection fraction: "
        f"{primary_metrics['event_detection_fraction']:.6f}"
    )
    print(
        "Random median associated episodes: "
        f"{random_summary['random_associated_count_median']:.3f}"
    )
    print(
        "Empirical p-value: "
        f"{random_summary['empirical_p_value']:.6f}"
    )
    print(
        "Evidence class: "
        f"{evidence_class}"
    )
    print()
    print(
        f"Episode associations: "
        f"{episode_associations_path}"
    )
    print(
        f"Event clusters: "
        f"{event_clusters_path}"
    )
    print(
        f"Random controls: "
        f"{random_controls_path}"
    )
    print(
        f"Sensitivity table: "
        f"{sensitivity_path}"
    )
    print(
        f"Summary: "
        f"{summary_path}"
    )
    print(
        f"Report: "
        f"{report_path}"
    )
    print(
        f"Manifest: "
        f"{manifest_path}"
    )
    print()
    print(
        "Interpretation boundary: retrospective "
        "specificity evaluation only."
    )


if __name__ == "__main__":
    main()


